title: "My webpage"
date: 2021-17-21
author: Kevin Viscafe
email: kevinviscafe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first github site

# social links
twitter_username: kevinsanbolivia # DO NOT include the @ character, or else the build will fail!
github_username:  kevinsanbolivia # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
